import { all } from "redux-saga/effects";

import cart from './cart/sagas';
import auth from './global/sagas';
// creating a async function generated by * and using yield as await (feat-fe use this in rootSaga),
// inside all we pass all the functions that need to be executed
export default function* rootSaga(): any {
  return yield all([
    cart,
    auth
  ])
}
